### ISSUE TITLE
Cake Plate Bake not creating database configuration

### ISSUE THREAD

**Issue by manuhabitela** [ProLoser/BakingPlate#13]
Hi,

When I try to create a new project with the console command `cake plate bake`, everything is working except the creation of the `config/database.php` file.
The error occurs when:
1. I type `cake plate bake` in the console
2. It asks me where I want to create my app: by default it says something like `localhost/app/myapp` so I correct it to `localhost/app`
3. Everything goes well until the creation of the `database.php` file: it tries to put it in `localhost/app/app/config`

Discovering the BakingPlate right now, it seems great ;)
Leimi

**Comment by ProLoser** [comment]
Delete the app folder and ron the command from localhost. I'm not sure
what's causing the behavior to Occur but in my experience has been customary
to just let t the console create the directory.

I will look into the issue however and let me know if there is anything you
feel should be added!

**Comment by ProLoser** [comment]
Should be fixed in the latest version. I forgot this was even open.

**Comment by manuhabitela** [comment]
Hey thanks, I'll try to test this soon and let you know :)

**Comment by manuhabitela** [comment]
Hey,
For the cakephp 1.3 branch, the bug is still there. No matter if I run the command from `localhost/` or `localhost/app/`, it wants to create the `database.php` file in `localhost/app/app/config/database.php`.
Runs well with the cakephp 2.0 branch though :)

edit: Just made a pull request with a tiny removal of code to let this work on 1.3.
